Pipa M.A Homework №3
w84fate/OTUS_py_learn pull request #3
Opened 2022-10-20 14:58 UTC by w84fate

2022-10-20 15:03 UTC, w84fate commented on homework_03/Dockerfile
> +CMD uvicorn main:app --host 0.0.0.0
Не смог сайт открыть из под Docker+WSL на локальном ПК, запускается сервер, но какие бы порты не подменял подключиться из браузера не смог. Тесты прошли поэтому похоже все верно, но если есть возможность подскажите как правильно прокинуть порт из под WSL

2022-10-20 15:06 UTC, w84fate commented on homework_03/README.md
> +- есть комментарий с информацией о том, как запускать этот контейнер
не понимаю что требовалось создать файл и добавить туда команды
sudo docker build . -t app и sudo docker run -it app ? не очень представляю как это должно выглядеть

2022-10-22 06:55 UTC, mahenzon commented on homework_03/README.md
> +- есть комментарий с информацией о том, как запускать этот контейнер
Хорошей практикой считается добавить в начало `Dockerfile` информацию о том, как запустить контейнер. То есть в данном случае на первых строчках в файле `homework_03/Dockerfile` можно написать
```
docker build . -t app 
docker run -it -p 8000:8000 app
```
Так что правильное предположение

2022-10-22 07:01 UTC, mahenzon requested changes
Хорошая работа. Нужно только сделать установку зависимостей до копирования всего приложения

2022-10-22 07:01 UTC, mahenzon commented on homework_03/.dockerignore
> +*.md
Лучше накидать сюда побольше, можно скопировать отсюда, например https://github.com/GoogleCloudPlatform/getting-started-python/blob/main/optional-kubernetes-engine/.dockerignore

2022-10-22 07:01 UTC, mahenzon commented on homework_03/Dockerfile
> +RUN pip install -r requirements.txt
эта строчка должна идти до того, как мы скопировали файлы внутрь Docker, но после того, как мы скопировали файл `requirements.txt`. Необходимо делать в два этапа
Вот как мы делали на занятии:
https://github.com/OtusTeam/BasePython/blob/bc578eb895ebbfee050413b0704fc8804afdcac5/lessons/lesson.13/Dockerfile#L15

2022-10-22 07:36 UTC, w84fate commented on homework_03/README.md
> +- есть комментарий с информацией о том, как запускать этот контейнер
Добавил как однострочные комментарии

2022-10-22 07:37 UTC, w84fate commented on homework_03/.dockerignore
> +*.md
добавил, указывал в проекте только то что лишнее у меня в проекте. Получается просто бест практикс накидывать сразу с запасом чтобы один раз настроить и больше его не трогать?

2022-10-22 07:38 UTC, w84fate commented on homework_03/Dockerfile
> +RUN pip install -r requirements.txt
добавил отдельное копирование зависимостей перед установкой. Но мне не очень понятно чем это хорошо, разве мы так дважды не копируем просто файл зависимостей и чем плохо устанавливать их после того как скопирован сразу весь проект?

2022-10-25 06:10 UTC, mahenzon commented on homework_03/README.md
> +- есть комментарий с информацией о том, как запускать этот контейнер
Отлично

2022-10-25 06:11 UTC, mahenzon commented on homework_03/.dockerignore
> +*.md
Да, лучше сразу накидать всё возможное, чтобы потом случайно не закоммитить чего лишнего

2022-10-25 06:13 UTC, mahenzon commented on homework_03/Dockerfile
> +RUN pip install -r requirements.txt
суть в том, что мы зависимости меняем редко, а файлы в проекте меняем постоянно. Так как мы хотим воспользоваться кэшированием слоёв, нам нужно самые тяжелые операции (например, установка зависимостей) вынести повыше, а операции полегче (например, копирование файлов) спустить пониже. Это избавит нас от установки зависимостей каждый раз, когда мы отредактировали файлы и пересобираем образ

2022-10-25 06:14 UTC, mahenzon commented on homework_03/Dockerfile
> +COPY . /var/app
тут можно сделать и `COPY . .`, так как мы выше указали, что работаем в этой директории: `WORKDIR /var/app`

2022-10-25 06:34 UTC, w84fate commented on homework_03/Dockerfile
> +RUN pip install -r requirements.txt
точно, спасибо)

2022-10-28 16:32 UTC, merged